name:           ast-builder
version:        0.1.0.0
github:         "arendsee/ast-builder"
license:        GPL-3
author:         "Zebulun Arendsee"
maintainer:     "zbwrnz@gmail.com"
copyright:      "2018 Zebulun Arendsee"
description:    Please see the README on GitHub at <https://github.com/arendsee/ast-builder#readme>
synopsis:       A toy repo for generating code from an AST
category:       Code Generation


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
    - base >= 4.7 && < 5
    - wl-pprint-text

library:
  source-dirs: src

executables:
  ast-builder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ast-builder
